### ISSUE TITLE
Usage with Slim 4.11 throws an Exception

### ISSUE THREAD

**Issue by swilking** [sapphirecat/slim4-http-interop-adapter#1]
Usage with Slim >= v4.11 throws an Exception:

Sapphirecat\Slim4HttpInteropAdapter\GuzzlePsr7v1Factory::$responseFactoryClass must be string

Instead of

    /** @var string */
    protected static $responseFactoryClass = 'Http\Factory\Guzzle\ResponseFactory';
    /** @var string */
    protected static $streamFactoryClass = 'Http\Factory\Guzzle\StreamFactory';
    /** @var string */
    protected static $serverRequestCreatorClass = 'GuzzleHttp\Psr7\ServerRequest';
    /** @var string */
    protected static $serverRequestCreatorMethod = 'fromGlobals';

the declaration must be

    /** @var string */
    protected static string $responseFactoryClass = 'Http\Factory\Guzzle\ResponseFactory';
    /** @var string */
    protected static string $streamFactoryClass = 'Http\Factory\Guzzle\StreamFactory';
    /** @var string */
    protected static string $serverRequestCreatorClass = 'GuzzleHttp\Psr7\ServerRequest';
    /** @var string */
    protected static string $serverRequestCreatorMethod = 'fromGlobals';

**Comment by sapphirecat** [comment]
I made two releases to update dependency specifications:

* v1.0.2: requires Slim `<4.11` and retains the minimum PHP 7.1
* v1.1.0: requires Slim `^4.11` and at least PHP 7.4

I think this should mean that composer will now choose the 1.0.2 or 1.1.0 versions, depending on which version of Slim (or PHP) is in use in projects.  However, I haven't tested it thoroughly from a user perspective, so please don't hesitate to open a new issue if there are any problems.
